language: python
python:
- 3.6.5
stages:
- Quality
- Publish
install:
- make install-dev
jobs:
  include:
  - stage: Quality
    name: lint
    script: make lint
  - name: tests
    script: make test
  - stage: Publish
    script: skip
    deploy:
      provider: pypi
      user: kyp76
      distributions: sdist bdist_wheel
      password:
        secure: bw8EhqxWjuIj2e7dcx7VoGgxeMHJKhEriQpeKc6C104GrmuM/z/Lyb7Tdf01KExoa31N6Zl2EXPgMDWv+DV3S0qLLwBYlSsVYx4mrVcdXqKoD0dWVk8RWaSY6ixaifKOpuRCvXBkAUs3ETl6bhpwkg/AeGD4xEw81niZkRV7xKt/+3oOBLE+1MGFPTnKDJDWSZe5tomNEml0Dq5tHGZSiIXPerdmy6T1vXY8VLJGSNIM71bTNwRJK3cECTc9Px++BUO/OfBO6E2EL6ivgKArlAzkGK5doOCpDndaQQb82PSbHVKcvbpgFl1uoFAbW0kSUnqz4t7JyJrIejh1iREzJ9daFId9ciZjLN8YUUarSqFKgY5YHfJMG+7YNGyROVf9kfC72T8cH6e39bNj2CEKhW+XjqAqGKM9Ski1QS9UIqwRaJG1kWm2Gr3vjXyEGVhwGgmVrPkMO1A7wAkcx0kXB4gqExRvT6QaZ7VXud0tLmL7qYjE4b8SxYFNEVAadXHKL3BVme76/xX0a9+APGlJzymF7vJ/uu+f3qKSeozsJl2qxjQytCemQfslohoJ/469y3BC9xz3/57BiVcp6YGY2P5XwFCdP7+Q8VXONW2jTBWvc/d/bH7BUI8rYYsn0rCkYA0pQXjwWzxfNeaoGkT9EImXnnBIyp4zFDWw44kJkpM=
      on:
        tags: true
    if: tag IS present
after_success: coveralls
